project:
  type: website

website:
  title: "José Enrique Pons Website"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/politeles

format:
  html:
    theme: cosmo
    css: styles.css



