project:
  type: website

website:
  title: "José Enrique Pons Website"
  google-analytics: "G-RQNWGYTYCC"
  open-graph: true

  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/politeles
resources:
  - "CNAME"
format:
  html:
    theme: cosmo
    css: styles.css



