baseURL = "https://jpons.es/"

title = "Jose Enrique Pons Personal Site"

theme = "hugo-coder"
publishdir = "docs"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

[params]
    author = "Jose Enrique Pons"
    description = "Jose Enrique Pons's personal website"
    keywords = "blog,developer,personal,ai,ml,artificial intelligence, machine learning"
    info = "Ph.D. Artificial Intelligence, Enterprise Architect"
    avatarurl = "images/profile.jpg"
    footercontent = "Welcome to my personal site"

    dateformat = "January 2, 2006"

    hideCredits = false
    hideCopyright = false

    # Git Commit in Footer, uncomment the line below to enable it.
    #commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Use inverted colors
    inverted = false

    # Series see also post count
    maxSeeAlsoItems = 5

    # Custom CSS
    custom_css = []
    
    # Custom JS
    custom_js = []
[permalinks]
  posts = "/:year/:month/:title/"
 
[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/politeles"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 3
    url = "https://twitter.com/jose_e_pons"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 4
    url = "https://www.linkedin.com/in/politeles"
[[params.social]]
    name = "Medium"
    icon = "fab fa-medium"
    weight = 5
    url = "https://medium.com/@jenrike.pons"


[languages]
    [languages.en]
        languagename = "English"

        [[languages.en.menu.main]]
        name = "About"
        weight = 1
        url = "/about/"

        [[languages.en.menu.main]]
        name = "Blog"
        weight = 2
        url = "/posts/"

        [[languages.en.menu.main]]
        name = "Projects"
        weight = 3
        url = "/projects/"

        [[languages.en.menu.main]]
        name = "Contact me"
        weight = 5
        url = "/contact/"
	[languages.es]
        languagename = "Español"
		 title = "Página personal de José Enrique Pons"

        [languages.es.params]
            author = "José Enrique Pons"
            info = "Doctor en Inteligencia Artificial, Arquitecto Empresarial"
            description = "Página personal de José Enrique Pons"
            keywords = "blog,doctor, inteligencia artificial, machine learning, aprendizaje automático"
            footercontent = "Bienvenidos a mi sitio personal"


        [[languages.es.menu.main]]
        name = "Sobre mí"
        weight = 1
        url = "/about/"

        [[languages.es.menu.main]]
        name = "Blog"
        weight = 2
        url = "/posts/"

        [[languages.es.menu.main]]
        name = "Projectos"
        weight = 3
        url = "/projects/"

        [[languages.es.menu.main]]
        name = "Contacto"
        weight = 5
        url = "/contact/"

